// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSRh5JHeMGbKyV0T6hxoJir4Yv59pFJzQ',
    appId: '1:116894699180:android:0c0ace7b9bd8d2a8219909',
    messagingSenderId: '116894699180',
    projectId: 'wallet-app-flutter-c420d',
    storageBucket: 'wallet-app-flutter-c420d.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChstKV9hyANYqR7UkrqXhNF8KLpNhf3Co',
    appId: '1:116894699180:ios:b0991f6f8da2e4cf219909',
    messagingSenderId: '116894699180',
    projectId: 'wallet-app-flutter-c420d',
    storageBucket: 'wallet-app-flutter-c420d.firebasestorage.app',
    iosBundleId: 'com.example.walletApp',
  );
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpTbk8iC6hf3o8s9TMs3ZDgHNSrUzlavU',
    appId: '1:116894699180:web:a7de49ba4cd651d2219909',
    messagingSenderId: '116894699180',
    projectId: 'wallet-app-flutter-c420d',
    authDomain: 'wallet-app-flutter-c420d.firebaseapp.com',
    storageBucket: 'wallet-app-flutter-c420d.firebasestorage.app',
    measurementId: 'G-P9TJXDPP91',
  );
}
